navires/nnf/urls.py
from django.urls import path
from . import views

app_name = 'nnf'
urlpatterns = [
    # post views
    path('', views.liste_navires, name='liste_navires'),
    path('navire/<int:id>', views.detail_navire, name='detail_navire'),
    path('navire/ajout', views.ajout_navire, name='ajout_navire'),
    path('navire/modif/<int:id>', views.modifier_navire, name='modifier_navire'),
    path('navire/supp/<int:id>', views.supprimer_navire, name='supprimer_navire'),
    path('personnes', views.liste_personnes, name='liste_personnes'),
    path('gens_de_mer', views.liste_gens_de_mer, name='liste_gens_de_mer'),
    path('personne/<int:id>', views.detail_personne, name='detail_personne'),
    path('personne/ajout', views.ajout_personne, name='ajout_personne'),
    path('personne/modif/<int:id>', views.modifier_personne, name='modifier_personne'),
    path('personne/modif2/<int:id>', views.modifier_personne_alt, name='modifier_personne_alt'),
    path('personne/supp/<int:id>', views.supprimer_personne, name='supprimer_personne'),
    path('proprietaires', views.liste_proprietaires, name='liste_proprietaires'),
    path('proprietaire/<int:id>', views.detail_proprietaire, name='detail_proprietaire'),
    path('proprietaire/ajout', views.ajout_proprietaire, name='ajout_proprietaire'),
    path('proprietaire/modif/<int:id>', views.modifier_proprietaire, name='modifier_proprietaire'),
    path('proprietaire/supp/<int:id>', views.supprimer_proprietaire, name='supprimer_proprietaire'),
    path('armateurs', views.liste_armateurs, name='liste_armateurs'),
    path('armateur/<int:id>', views.detail_armateur, name='detail_armateur'),
    path('armateur/ajout', views.ajout_armateur, name='ajout_armateur'),
    path('armateur/modif/<int:id>', views.modifier_armateur, name='modifier_armateur'),
    path('armateur/supp/<int:id>', views.supprimer_armateur, name='supprimer_armateur'),
    path('traversees', views.liste_traversees, name='liste_traversees'),
    path('traversee/<int:id>', views.detail_traversee, name='detail_traversee'),
    path('traversee/ajout/<int:navire_id>', views.ajout_traversee, name='ajout_traversee'),
    path('traversee/modif/<int:id>', views.modifier_traversee, name='modifier_traversee'),
    path('traversee/supp/<int:id>', views.supprimer_traversee, name='supprimer_traversee'),
    path('a_n_t/ajout/<int:traversee_id>', views.ajout_autre_navire_traversee, name='ajout_autre_navire_traversee'),
    path('a_n_t/<int:id>', views.detail_autre_navire_traversee, name='detail_autre_navire_traversee'),
    path('a_n_t/modif/<int:id>', views.modifier_autre_navire_traversee, name='modifier_autre_navire_traversee'),
    path('voyage/<int:id>', views.detail_voyage, name='detail_voyage'),
    path('voyage/ajout/<int:personne_id>', views.ajout_voyage, name='ajout_voyage'),
    path('voyage/modif/<int:id>', views.modifier_voyage, name='modifier_voyage'),
    path('voyage/supp/<int:id>', views.supprimer_voyage, name='supprimer_voyage'),
]

navires/nnf/templates/base.html
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Base{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link href="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.css" rel="stylesheet">
    </head>
    <body>
        {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Navires de Nouvelle-France</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">Accueil</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Navires</a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li><a class="dropdown-item" href="{% url 'nnf:liste_navires' %}">Tous les navires</a></li>
                                    <li><a class="dropdown-item" href="{% url 'nnf:liste_traversees' %}">Toutes les traversées</a></li>
                                    <li><a class="dropdown-item" href="{% url 'nnf:liste_armateurs' %}">Tous les armateurs</a></li>
                                    <li><a class="dropdown-item" href="{% url 'nnf:liste_proprietaires' %}">Tous les propriétaires</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Personnes</a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li><a class="dropdown-item" href="{% url 'nnf:liste_personnes' %}">Toutes les personnes</a></li>
                                    <li><a class="dropdown-item" href="{% url 'nnf:liste_gens_de_mer' %}">Gens de mer</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                {% if user.is_authenticated %}
                                    {% if user.first_name %}
                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.first_name }}</a>
                                    {% else %}
                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                                    {% endif %}
                                {% else %}
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Connexion</a>
                                {% endif %}
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">Déconnexion</a></li>
                                    {% else %}
                                        <li><a class="dropdown-item" href="{% url 'account:login' %}">Connexion</a></li>
                                        <li><a class="dropdown-item" href="{% url 'account:register_account' %}">Inscription</a></li>
                                    {% endif %}
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        {% endblock %}
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% elif message.tags == "warning" %}
                    <div class="alert alert-warning mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% elif message.tags == "info" %}
                    <div class="alert alert-info mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% elif message.tags == "success" %}
                    <div class="alert alert-success mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% else %}
                    <div class="alert alert-debug mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <footer class="text-center text-lg-start bg-light text-muted mt-4">
            <div class="text-center p-4">Fin de la page</div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
        </script>
        <script src="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.js"></script>
    </body>
</html>

navires/nnf/templates/index.html
{% extends "base.html" %}
{% block title %}Navires de Nouvelle-France{% endblock %}
{% block content %}
    <div class="container">
        <h1>Page de bienvenue</h1>
    </div>
{% endblock %}