navires/nnf/urls.py
from django.urls import path
from . import views

app_name = 'nnf'
urlpatterns = [
    # post views
    path('', views.liste_navires, name='liste_navires'),
    path('navire/<int:id>', views.detail_navire, name='detail_navire'),
    path('navire/ajout', views.ajout_navire, name='ajout_navire'),
    path('navire/modif/<int:id>', views.modifier_navire, name='modifier_navire'),
    path('navire/supp/<int:id>', views.supprimer_navire, name='supprimer_navire'),
    path('personnes', views.liste_personnes, name='liste_personnes'),
    path('gens_de_mer', views.liste_gens_de_mer, name='liste_gens_de_mer'),
    path('personne/<int:id>', views.detail_personne, name='detail_personne'),
    path('personne/ajout', views.ajout_personne, name='ajout_personne'),
    path('personne/modif/<int:id>', views.modifier_personne, name='modifier_personne'),
    path('personne/modif2/<int:id>', views.modifier_personne_alt, name='modifier_personne_alt'),
    path('personne/supp/<int:id>', views.supprimer_personne, name='supprimer_personne'),
    path('proprietaires', views.liste_proprietaires, name='liste_proprietaires'),
    path('proprietaire/<int:id>', views.detail_proprietaire, name='detail_proprietaire'),
    path('proprietaire/ajout', views.ajout_proprietaire, name='ajout_proprietaire'),
    path('proprietaire/modif/<int:id>', views.modifier_proprietaire, name='modifier_proprietaire'),
    path('proprietaire/supp/<int:id>', views.supprimer_proprietaire, name='supprimer_proprietaire'),
    path('armateurs', views.liste_armateurs, name='liste_armateurs'),
    path('armateur/<int:id>', views.detail_armateur, name='detail_armateur'),
    path('armateur/ajout', views.ajout_armateur, name='ajout_armateur'),
    path('armateur/modif/<int:id>', views.modifier_armateur, name='modifier_armateur'),
    path('armateur/supp/<int:id>', views.supprimer_armateur, name='supprimer_armateur'),
    path('traversees', views.liste_traversees, name='liste_traversees'),
    path('traversee/<int:id>', views.detail_traversee, name='detail_traversee'),
    path('traversee/ajout/<int:navire_id>', views.ajout_traversee, name='ajout_traversee'),
    path('traversee/modif/<int:id>', views.modifier_traversee, name='modifier_traversee'),
    path('traversee/supp/<int:id>', views.supprimer_traversee, name='supprimer_traversee'),
    path('a_n_t/ajout/<int:traversee_id>', views.ajout_autre_navire_traversee, name='ajout_autre_navire_traversee'),
    path('a_n_t/<int:id>', views.detail_autre_navire_traversee, name='detail_autre_navire_traversee'),
    path('a_n_t/modif/<int:id>', views.modifier_autre_navire_traversee, name='modifier_autre_navire_traversee'),
    path('voyage/<int:id>', views.detail_voyage, name='detail_voyage'),
    path('voyage/ajout/<int:personne_id>', views.ajout_voyage, name='ajout_voyage'),
    path('voyage/modif/<int:id>', views.modifier_voyage, name='modifier_voyage'),
    path('voyage/supp/<int:id>', views.supprimer_voyage, name='supprimer_voyage'),
]

navires/nnf/templates/navires/ajout.html
{% extends 'base.html' %}

{% block title %}Ajouter un navire{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Ajouter un Navire</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                            <a href="{% url 'nnf:liste_navires' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/navires/detail.html
{% extends "base.html" %}

{% block title %}Navire - Vue détaillée{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Vue détaillée: {{ navire.nom }}</h1>
        </div>
        <p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Attribut</th>
                        <th scope="col">Valeur</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Nom</td>
                        <td>{{ navire.nom }}</td>
                    </tr>
                    <tr>
                        <td>Propriétaire</td>
                        {% if navire.proprietaire %}
                            <td>{{ navire.proprietaire }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Armateur</td>
                        {% if navire.armateur %}
                            <td>{{ navire.armateur }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Tonnage</td>
                        {% if navire.tonnage %}
                            <td>{{ navire.tonnage }}</td>
                        {% else %}
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Ajouté par</td>
                        <td>{{ navire.aud_crt_user.username }}</td>
                    </tr>
                    <tr>
                        <td>Ajouté le</td>
                        <td>{{ navire.aud_crt_ts }}</td>
                    </tr>
                    {% if navire.aud_upd_user %}
                        <tr>
                            <td>Mis à jour par</td>
                            <td>{{ navire.aud_upd_user.username }}</td>
                        </tr>
                        <tr>
                            <td>Mis à jour le</td>
                            <td>{{ navire.aud_upd_ts }}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        <hr />
        <h3>Traversées</h3>
        <ul class="list-group">
            {% if traversees %}
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Maître</th>
                            <th scope="col">Origine</th>
                            <th scope="col">Date de départ</th>
                            <th scope="col">Destination</th>
                            <th scope="col">Date de d'arrivée</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for t in traversees %}
                            <tr>
                                <td>
                                    {% if t.maitre %} {{ t.maitre.nom }}, {{ t.maitre.prenom }} {% else %} Inconnu {% endif %}
                                </td>
                                <td>
                                    {% if t.depart_lieu %} {{ t.depart_lieu }} {% else %} Inconnue {% endif %}
                                </td>
                                <td>
                                    {% if t.depart_date %}
                                        {{ t.depart_date }}
                                    {% elif t.depart_annee %}
                                        {{ t.depart_annee }}
                                    {% else %}
                                        Inconnue
                                    {% endif %}
                                </td>
                                <td>
                                    {% if t.arrivee_lieu %} {{ t.arrivee_lieu }} {% else %} Inconnue {% endif %}
                                </td>
                                <td>
                                    {% if t.arrivee_date %}
                                        {{ t.arrivee_date }}
                                    {% elif t.arrivee_annee %}
                                        {{ t.arrivee_annee }}
                                    {% else %}
                                        Inconnue
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Pas de traversée.
            {% endif %}
        </ul>
        <hr />
        </p>
        <p>
            <a href="{% url 'nnf:liste_navires' %}" class="btn btn-primary">Retour à la liste</a>
        </p>
    </div>
{% endblock %}

navires/nnf/templates/navires/liste.html
{% extends "base.html" %}

{% block title %}Liste des navires{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Liste des Navires</h1>
    </div>
    <p>
        <a href="{% url 'nnf:ajout_navire' %}" class="btn btn-primary">Ajouter un navire</a>
        <table id="table"
               data-toggle="table"
               data-search="true"
               data-show-columns="true"
               data-pagination="true"
               data-page-size="25"
               data-page-list="[25, 50, 100, 250, 500, all]"
               data-response-handler="responseHandler">
            <thead>
                <tr>
                    <th data-field="nom" data-sortable="true">Nom</th>
                    <th data-field="proprietaire" data-sortable="true">Propriétaire</th>
                    <th data-field="armateur" data-sortable="true">Armateur</th>
                    <th data-field="actions" data-sortable="false">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for n in navires %}
                    <tr>
                        <td>
                            {{ n.nom }}
                        </td>
                        {% if n.proprietaire %}
                            <td>{{ n.proprietaire }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                        {% if n.armateur %}
                            <td>{{ n.armateur }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                        <td class="text-center">
                            <a href="{% url 'nnf:detail_navire' n.id  %}"
                                class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Détail">
                                <span class="bi-eye"></span>
                            </a>
                            <a href="{% url 'nnf:modifier_navire' n.id %}"
                               class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier">
                                <span class="bi-pencil"></span>
                            </a>
                            <a href="{% url 'nnf:supprimer_navire' n.id %}"
                               class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Supprimer">
                               <span class="bi-trash"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

navires/nnf/templates/navires/modif.html
{% extends 'base.html' %}

{% block title %}Modifier un nvire{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Modifier un navire</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Modifier</button>
                            <a href="{% url 'nnf:liste_navires' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                    <hr>
                    <h2>Traversées</h2>
                    {% if traversees %}
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Départ</th>
                                    <th scope="col">Arrivée</th>
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for t in traversees %}
                                    <tr>
                                        <td>
                                            {% if t.depart_annee %}
                                                {{ t.depart_annee }},
                                            {% else %}
                                                Date inconnue,
                                            {% endif %}
                                            {% if t.depart_lieu %}
                                                {{ t.depart_lieu }}
                                            {% else %}
                                                d'un lieu inconnu
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if t.arrivee_annee %}
                                                {{ t.arrivee_annee }},
                                            {% else %}
                                                Date inconnue,
                                            {% endif %}
                                            {% if t.arrivee_lieu %}
                                                {{ t.arrivee_lieu }}
                                            {% else %}
                                                vers un lieu inconnu
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'nnf:modifier_traversee' t.id %}"
                                               class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier">
                                               <span class="bi-pencil"></span>
                                            </a>
                                            <a href="{% url 'nnf:supprimer_traversee' t.id %}"
                                               class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Supprimer">
                                               <span class="bi-trash"></span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>Pas de traversée.</p>
                    {% endif %}
                    <a href="{% url 'nnf:ajout_traversee' navire.id %}" class="btn btn-primary">Ajouter une traversée</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/navires/supp.html
{% extends "base.html" %}

{% block title %}Supprimer un navire{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Supprimer le navire {{ navire.nom }}</h1>
        </div>
        <div class="module">
            <form action="" method="post">
                {% csrf_token %}
                <p>Es-tu sûr de vouloir supprimer ce navire?</p>
                <p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Attribut</th>
                                <th scope="col">Valeur</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Nom</td>
                                <td>{{ navire.nom }}</td>
                            </tr>
                            <tr>
                                <td>Propriétaire</td>
                                {% if navire.proprietaire %}
                                    <td>{{ navire.proprietaire }}</td>
                                {% else %}
                                    <td>Inconnu</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>Armateur</td>
                                {% if navire.armateur %}
                                    <td>{{ navire.armateur }}</td>
                                {% else %}
                                    <td>Inconnu</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>Tonnage</td>
                                {% if navire.tonnage %}
                                    <td>{{ navire.tonnage }}</td>
                                {% else %}
                                    <td>&nbsp;</td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>
                </p>
                <p>
                    <button type="submit" class="btn btn-primary">Oui</button>
                    <a href="{% url 'nnf:liste_navires' %}" class="btn btn-primary">Non</a>
                </p>
            </form>
        </div>
    </div>
{% endblock %}