navires/nnf/urls.py
from django.urls import path
from . import views

app_name = 'nnf'
urlpatterns = [
    # post views
    path('', views.liste_navires, name='liste_navires'),
    path('navire/<int:id>', views.detail_navire, name='detail_navire'),
    path('navire/ajout', views.ajout_navire, name='ajout_navire'),
    path('navire/modif/<int:id>', views.modifier_navire, name='modifier_navire'),
    path('navire/supp/<int:id>', views.supprimer_navire, name='supprimer_navire'),
    path('personnes', views.liste_personnes, name='liste_personnes'),
    path('gens_de_mer', views.liste_gens_de_mer, name='liste_gens_de_mer'),
    path('personne/<int:id>', views.detail_personne, name='detail_personne'),
    path('personne/ajout', views.ajout_personne, name='ajout_personne'),
    path('personne/modif/<int:id>', views.modifier_personne, name='modifier_personne'),
    path('personne/modif2/<int:id>', views.modifier_personne_alt, name='modifier_personne_alt'),
    path('personne/supp/<int:id>', views.supprimer_personne, name='supprimer_personne'),
    path('proprietaires', views.liste_proprietaires, name='liste_proprietaires'),
    path('proprietaire/<int:id>', views.detail_proprietaire, name='detail_proprietaire'),
    path('proprietaire/ajout', views.ajout_proprietaire, name='ajout_proprietaire'),
    path('proprietaire/modif/<int:id>', views.modifier_proprietaire, name='modifier_proprietaire'),
    path('proprietaire/supp/<int:id>', views.supprimer_proprietaire, name='supprimer_proprietaire'),
    path('armateurs', views.liste_armateurs, name='liste_armateurs'),
    path('armateur/<int:id>', views.detail_armateur, name='detail_armateur'),
    path('armateur/ajout', views.ajout_armateur, name='ajout_armateur'),
    path('armateur/modif/<int:id>', views.modifier_armateur, name='modifier_armateur'),
    path('armateur/supp/<int:id>', views.supprimer_armateur, name='supprimer_armateur'),
    path('traversees', views.liste_traversees, name='liste_traversees'),
    path('traversee/<int:id>', views.detail_traversee, name='detail_traversee'),
    path('traversee/ajout/<int:navire_id>', views.ajout_traversee, name='ajout_traversee'),
    path('traversee/modif/<int:id>', views.modifier_traversee, name='modifier_traversee'),
    path('traversee/supp/<int:id>', views.supprimer_traversee, name='supprimer_traversee'),
    path('a_n_t/ajout/<int:traversee_id>', views.ajout_autre_navire_traversee, name='ajout_autre_navire_traversee'),
    path('a_n_t/<int:id>', views.detail_autre_navire_traversee, name='detail_autre_navire_traversee'),
    path('a_n_t/modif/<int:id>', views.modifier_autre_navire_traversee, name='modifier_autre_navire_traversee'),
    path('voyage/<int:id>', views.detail_voyage, name='detail_voyage'),
    path('voyage/ajout/<int:personne_id>', views.ajout_voyage, name='ajout_voyage'),
    path('voyage/modif/<int:id>', views.modifier_voyage, name='modifier_voyage'),
    path('voyage/supp/<int:id>', views.supprimer_voyage, name='supprimer_voyage'),
]

navires/nnf/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Proprietaire(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='proprio_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='proprio_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.nom


class Armateur(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='armateur_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='armateur_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.nom


class Navire(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    proprietaire = models.ForeignKey(Proprietaire, on_delete=models.RESTRICT, related_name='liste_navires', null=True, default=None)
    armateur = models.ForeignKey(Armateur, on_delete=models.RESTRICT, related_name='liste_navires', null=True, default=None)
    tonnage = models.IntegerField(null=True, default=0)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='navire_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='navire_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.nom


class Personne(models.Model):
    CHOIX_LISTE = [
        (0, "Indéfini"),
        (1, "Administrateurs"),
        (2, "Émigrants repassés en France"),
        (3, "Engagés"),
        (4, "Filles du roi et filles à marier"),
        (5, "Gens de Mer"),
        (6, "Marchands"),
        (7, "Militaires"),
        (8, "Religieux"),
        (9, "Volontaires et autres immigrants"),
    ]
    nom = models.CharField(max_length=50, null=False)
    prenom = models.CharField(max_length=50, null=False)
    variation_du_nom = models.CharField(max_length=100, null=True, blank=True, default='')
    titre = models.CharField(max_length=50, null=True, blank=True, default='')
    naissance_annee = models.SmallIntegerField(null=True, blank=True, default='')
    naissance_mois = models.SmallIntegerField(null=True, blank=True, default='')
    naissance_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    naissance_date = models.DateField(null=True)
    naissance_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    deces_annee = models.SmallIntegerField(null=True, blank=True, default='')
    deces_mois = models.SmallIntegerField(null=True, blank=True, default='')
    deces_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    deces_date = models.DateField(null=True)
    deces_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    note_biographique = models.CharField(max_length=2048, null=True, blank=True, default='')
    liste = models.SmallIntegerField(null=False, default=0, choices=CHOIX_LISTE)
    origine_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='personne_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='personne_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom + ', ' + self.prenom


class Traversee(models.Model):
    navire = models.ForeignKey(Navire, on_delete=models.RESTRICT, related_name='a_fait', null=False)
    objectif = models.CharField(max_length=50, null=True, blank=True, default='')
    depart_annee = models.SmallIntegerField(null=True, blank=True, default='')
    depart_mois = models.SmallIntegerField(null=True, blank=True, default='')
    depart_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    depart_date = models.DateField(null=True)
    depart_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    arrivee_annee = models.SmallIntegerField(null=True, blank=True, default='')
    arrivee_mois = models.SmallIntegerField(null=True, blank=True, default='')
    arrivee_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    arrivee_date = models.DateField(null=True)
    arrivee_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    destination = models.CharField(max_length=100, null=True, blank=True, default='')
    retour = models.CharField(max_length=100, null=True, blank=True, default='')
    notes_equipage_passagers = models.CharField(max_length=2048, null=True, blank=True, default='')
    observations = models.CharField(max_length=4096, null=True, blank=True, default='')
    nb_autres_navires = models.SmallIntegerField(null=False, default=0)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='traversee_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='traversee_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.navire.nom + '-' + str(self.depart_annee) + '-' + self.depart_lieu


class Autre_Navire_Traversee(models.Model):
    navire = models.ForeignKey(Navire, on_delete=models.RESTRICT, related_name='etait_dans', null=False)
    traversee = models.ForeignKey(Traversee, on_delete=models.CASCADE, related_name='comportait_aussi', null=False)
    observations = models.CharField(max_length=2048, null=True, blank=True, default='')
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='autre_navire_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='autre_navire_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)


class Voyage(models.Model):
    CHOIX_ROLE = [
        (0, "Indéfini"),
        (2, "Capitaine"),
        (6, "Contrôleur"),
        (1, "Maître"),
        (4, "Membre d'équipage"),
        (5, "Passager"),
        (3, "Pilote"),
    ]
    personne = models.ForeignKey(Personne, on_delete=models.RESTRICT, related_name='voyage_effectue', null=False)
    annee = models.SmallIntegerField(null=True, blank=True, default='')
    sequence = models.SmallIntegerField(null=False, default=1)
    destination = models.CharField(max_length=100, null=True, blank=True, default='')
    navire_nom = models.CharField(max_length=100, null=True, blank=True, default='')
    traversee = models.ForeignKey(Traversee, on_delete=models.RESTRICT, related_name='liste_passagers', null=True, default=None)
    role = models.SmallIntegerField(null=False, default=0, choices=CHOIX_ROLE)
    uk = models.UniqueConstraint(name='voyage_uk', fields=["personne_id", "annee", "sequence"])
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='voyage_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='voyage_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)

navires/nnf/templates/personnes/ajout.html
{% extends 'base.html' %}

{% block title %}Ajouter une personne{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Ajouter une personne</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                            <a href="{% url 'nnf:liste_personnes' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/personnes/detail.html
{% extends "base.html" %}

{% block title %}Personne - Vue détaillée{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Vue détaillée: {{ personne.nom }}, {{ personne.prenom }}</h1>
        </div>
        <p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Attribut</th>
                        <th scope="col">Valeur</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Nom</td>
                        <td>{{ personne.nom }}</td>
                    </tr>
                    <tr>
                        <td>Prénom</td>
                        <td>{{ personne.prenom }}</td>
                    </tr>
                    <tr>
                        <td>Variation du nom</td>
                        <td>{% if personne.variation_du_nom %} {{ personne.variation_du_nom }} {% else %} Aucune {% endif %}</td>
                    </tr>
                    <tr>
                        <td>Liste</td>
                        <td>{{ personne.get_liste_display }}</td>
                    <tr>
                    <tr>
                        <td>Lieu d'origine</td>
                        <td>{% if personne.origine_lieu %} {{ personne.origine_lieu }} {% else %} Inconnu {% endif %}</td>
                    <tr>
                        <td>Titre</td>
                        <td>{% if personne.titre %} {{ personne.titre }} {% else %} Inconnu {% endif %}</td>
                    </tr>
                    <tr>
                        <td>Naissance</td>
                        <td>
                            {% if personne.naissance_date %}
                                {{ personne.naissance_date }}
                            {% elif personne.naissance_annee %}
                                {{ personne.naissance_annee }}
                            {% else %}
                                Inconnue
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Lieu de naissance</td>
                        <td>
                            {% if personne.naissance_lieu %}
                                {{ personne.naissance_lieu }}
                            {% else %}
                                Inconnu
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Décès</td>
                        <td>
                            {% if personne.deces_date %}
                                {{ personne.deces_date }}
                            {% elif personne.deces_annee %}
                                {{ personne.deces_annee }}
                            {% else %}
                                Inconnu
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Lieu de décès</td>
                        <td>
                            {% if personne.deces_lieu %}
                                {{ personne.deces_lieu }}
                            {% else %}
                                Inconnu
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Ajouté par</td>
                        <td>{{ personne.aud_crt_user.username }}</td>
                    </tr>
                    <tr>
                        <td>Ajouté le</td>
                        <td>{{ personne.aud_crt_ts }}</td>
                    </tr>
                    {% if personne.aud_upd_user %}
                        <tr>
                            <td>Mis à jour par</td>
                            <td>{{ personne.aud_upd_user.username }}</td>
                        </tr>
                        <tr>
                            <td>Mis à jour le</td>
                            <td>{{ personne.aud_upd_ts }}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
            {% if personne.note_biographique %}
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Notes biographiques</h3>
                        <p class="card-text">{{ personne.note_biographique }}</p>
                    </div>
                </div>
            {% endif %}
        <hr />
        <h3>Voyages</h3>
            {% if voyages %}
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Voyage</th>
                            <th scope="col">Navire</th>
                            <th scope="col">Rôle</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for v in voyages %}
                            <tr>
                                <td>{{ v.annee }}-{{ v.sequence }}</td>
                                <td>{{ v.traversee.navire.nom }}</td>
                                <td>{{ v.get_role_display }}</td>
                            </tr>
                        {% endfor %}
                   </tbody>
                </table>
            {% else %}
                Pas de voyage.
            {% endif %}
        <hr>
        <p>
            <a href="{% url 'nnf:liste_personnes' %}" class="btn btn-primary">Retour à la liste</a>
        </p>
    </div>
{% endblock %}

navires/nnf/templates/personnes/liste.html
{% extends "base.html" %}

{% block title %}Liste {{ liste }}{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="page-header">
        <h1>Liste {{ liste }}</h1>
    </div>
    <p>
        <a href="{% url 'nnf:ajout_personne' %}" class="btn btn-primary">Ajouter une personne</a>
        <table id="table"
               data-toggle="table"
               data-search="true"
               data-show-columns="true"
               data-pagination="true"
               data-page-size="500"
               data-page-list="[25, 50, 100, 250, 500, all]"
               data-response-handler="responseHandler">
            <thead>
                <tr>
                    <th data-field="nom" data-sortable="true">Nom</th>
                    <th data-field="origine" data-sortable="true">Lieu d'origine</th>
                    <th data-field="liste" data-sortable="true">Liste</th>
                    <th data-field="date_creation" data-sortable="true">Date création</th>
                    {% if user.is_authenticated %}
                        <th>Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for p in personnes %}
                    <tr>
                        <td>
                            {{ p.nom }}, {{ p.prenom }}
                            {% if p.naissance_annee or p.deces_annee %}
                                ({% if p.naissance_annee %}{{ p.naissance_annee }}{% endif %}-{% if p.deces_annee %}{{ p.deces_annee }}{% endif %})
                            {% endif %}
                            {% if p.titre %}&nbsp;({{ p.titre }}){% endif %}
                            {% if p.variation_du_nom %}&nbsp;Var.: ({{ p.variation_du_nom }}){% endif %}
                        </td>
                        <td>{% if p.origine_lieu %}
                                {{ p.origine_lieu }}
                            {% else %}
                                Inconnu
                            {% endif %}
                        </td>
                        <td>{{ p.get_liste_display }}</td>
                        <td>{% if p.aud_crt_ts %}
                                {{ p.aud_crt_ts }}
                            {% else %}
                                Indéfinie
                            {% endif %}
                        </td>
                        {% if user.is_authenticated %}
                            <td class="text-center">
                                <a href="{% url 'nnf:detail_personne' p.id %}"
                                class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Détail">
                                    <span class="bi-eye"></span>
                                </a>
                                <a href="{% url 'nnf:modifier_personne' p.id %}"
                                class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier (info de base)">
                                    <span class="bi-pencil"></span>
                                </a>
                                <a href="{% url 'nnf:modifier_personne_alt' p.id %}"
                                class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier (autre)">
                                    <span class="bi-pencil"></span>
                                </a>
                                <a href="{% url 'nnf:supprimer_personne' p.id %}"
                                class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Supprimer">
                                <span class="bi-trash"></span>
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

navires/nnf/templates/personnes/modif.html
{% extends 'base.html' %}

{% block title %}Modifier une personne{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Modifier une personne: {{ personne.nom }}, {{ personne.prenom }}</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Modifier</button>
                            <a href="{% url 'nnf:liste_personnes' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/personnes/modif2.html
{% extends 'base.html' %}

{% block title %}Modifier une personne{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Modifier une personne: {{ personne.nom }}, {{ personne.prenom }}</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <hr>
                    <h2>Voyages</h2>
                    {% if voyages %}
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Voyage</th>
                                    <th scope="col">Navire</th>
                                    <th scope="col">Rôle</th>
                                    <th scope="col">Destination</th>
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for v in voyages %}
                                    <tr>
                                        <td>{{ v.annee }} - {{ v.sequence }}</td>
                                        <td>{{ v.traversee.navire.nom }}</td>
                                        <td>{{ v.get_role_display }}</td>
                                        <td>
                                            {% if v.traversee.arrivee_lieu %}
                                                Traversée vers {{ v.traversee.arrivee_lieu }}
                                            {% elif v.destination %}
                                                Voyage vers:{{ v.destination }}
                                            {% else  %}
                                                Inconnue
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'nnf:detail_voyage' v.id %}"
                                               class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Detail">
                                               <span class="bi-eye"></span>
                                            </a>
                                            <a href="{% url 'nnf:modifier_voyage' v.id %}"
                                               class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier">
                                               <span class="bi-pencil"></span>
                                            </a>
                                            <a href="{% url 'nnf:supprimer_voyage' v.id %}"
                                               class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Supprimer">
                                               <span class="bi-trash"></span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>Pas de voyage.</p>
                    {% endif %}
                    <a href="{% url 'nnf:ajout_voyage' personne.id %}" class="btn btn-primary">Ajouter un voyage</a>
                    <a href="{% url 'nnf:modifier_personne' personne.id %}" class="btn btn-primary">Modifier info de base</a>
                    <a href="{% url 'nnf:liste_personnes' %}" class="btn btn-primary">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/personnes/supp.html
{% extends "base.html" %}

{% block title %}Supprimer une personne{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Supprimer la personne {{ personne.nom }}</h1>
        </div>
        <div class="module">
            <form action="" method="post">
                {% csrf_token %}
                <p>Es-tu sûr de vouloir supprimer cette personne?</p>
                <p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Attribut</th>
                                <th scope="col">Valeur</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Nom</td>
                                <td>{{ personne.nom }}</td>
                            </tr>
                            <tr>
                                <td>Prénom</td>
                                <td>{{ personne.prenom }}</td>
                            </tr>
                            <tr>
                                <td>Naissance</td>
                                <td>
                                    {% if p.naissance_date %}
                                        {{ p.naissance_date }}
                                    {% elif p.naissance_annee %}
                                        {{ p.naissance_annee }}
                                    {% else %}
                                        Inconnue
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>Décès</td>
                                <td>
                                    {% if p.deces_date %}
                                        {{ p.deces_date }}
                                    {% elif p.deces_annee %}
                                        {{ p.deces_annee }}
                                    {% else %}
                                        Inconnue
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </p>
                <p>
                    <button type="submit" class="btn btn-primary">Oui</button>
                    <a href="{% url 'nnf:liste_personnes' %}" class="btn btn-primary">Non</a>
                </p>
            </form>
        </div>
    </div>
{% endblock %}