navires/nnf/urls.py
from django.urls import path
from . import views

app_name = 'nnf'
urlpatterns = [
    # post views
    path('', views.liste_navires, name='liste_navires'),
    path('navire/<int:id>', views.detail_navire, name='detail_navire'),
    path('navire/ajout', views.ajout_navire, name='ajout_navire'),
    path('navire/modif/<int:id>', views.modifier_navire, name='modifier_navire'),
    path('navire/supp/<int:id>', views.supprimer_navire, name='supprimer_navire'),
    path('personnes', views.liste_personnes, name='liste_personnes'),
    path('gens_de_mer', views.liste_gens_de_mer, name='liste_gens_de_mer'),
    path('personne/<int:id>', views.detail_personne, name='detail_personne'),
    path('personne/ajout', views.ajout_personne, name='ajout_personne'),
    path('personne/modif/<int:id>', views.modifier_personne, name='modifier_personne'),
    path('personne/modif2/<int:id>', views.modifier_personne_alt, name='modifier_personne_alt'),
    path('personne/supp/<int:id>', views.supprimer_personne, name='supprimer_personne'),
    path('proprietaires', views.liste_proprietaires, name='liste_proprietaires'),
    path('proprietaire/<int:id>', views.detail_proprietaire, name='detail_proprietaire'),
    path('proprietaire/ajout', views.ajout_proprietaire, name='ajout_proprietaire'),
    path('proprietaire/modif/<int:id>', views.modifier_proprietaire, name='modifier_proprietaire'),
    path('proprietaire/supp/<int:id>', views.supprimer_proprietaire, name='supprimer_proprietaire'),
    path('armateurs', views.liste_armateurs, name='liste_armateurs'),
    path('armateur/<int:id>', views.detail_armateur, name='detail_armateur'),
    path('armateur/ajout', views.ajout_armateur, name='ajout_armateur'),
    path('armateur/modif/<int:id>', views.modifier_armateur, name='modifier_armateur'),
    path('armateur/supp/<int:id>', views.supprimer_armateur, name='supprimer_armateur'),
    path('traversees', views.liste_traversees, name='liste_traversees'),
    path('traversee/<int:id>', views.detail_traversee, name='detail_traversee'),
    path('traversee/ajout/<int:navire_id>', views.ajout_traversee, name='ajout_traversee'),
    path('traversee/modif/<int:id>', views.modifier_traversee, name='modifier_traversee'),
    path('traversee/supp/<int:id>', views.supprimer_traversee, name='supprimer_traversee'),
    path('a_n_t/ajout/<int:traversee_id>', views.ajout_autre_navire_traversee, name='ajout_autre_navire_traversee'),
    path('a_n_t/<int:id>', views.detail_autre_navire_traversee, name='detail_autre_navire_traversee'),
    path('a_n_t/modif/<int:id>', views.modifier_autre_navire_traversee, name='modifier_autre_navire_traversee'),
    path('voyage/<int:id>', views.detail_voyage, name='detail_voyage'),
    path('voyage/ajout/<int:personne_id>', views.ajout_voyage, name='ajout_voyage'),
    path('voyage/modif/<int:id>', views.modifier_voyage, name='modifier_voyage'),
    path('voyage/supp/<int:id>', views.supprimer_voyage, name='supprimer_voyage'),
]

navires/nnf/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Proprietaire(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='proprio_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='proprio_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.nom


class Armateur(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='armateur_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='armateur_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.nom


class Navire(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    proprietaire = models.ForeignKey(Proprietaire, on_delete=models.RESTRICT, related_name='liste_navires', null=True, default=None)
    armateur = models.ForeignKey(Armateur, on_delete=models.RESTRICT, related_name='liste_navires', null=True, default=None)
    tonnage = models.IntegerField(null=True, default=0)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='navire_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='navire_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.nom


class Personne(models.Model):
    CHOIX_LISTE = [
        (0, "Indéfini"),
        (1, "Administrateurs"),
        (2, "Émigrants repassés en France"),
        (3, "Engagés"),
        (4, "Filles du roi et filles à marier"),
        (5, "Gens de Mer"),
        (6, "Marchands"),
        (7, "Militaires"),
        (8, "Religieux"),
        (9, "Volontaires et autres immigrants"),
    ]
    nom = models.CharField(max_length=50, null=False)
    prenom = models.CharField(max_length=50, null=False)
    variation_du_nom = models.CharField(max_length=100, null=True, blank=True, default='')
    titre = models.CharField(max_length=50, null=True, blank=True, default='')
    naissance_annee = models.SmallIntegerField(null=True, blank=True, default='')
    naissance_mois = models.SmallIntegerField(null=True, blank=True, default='')
    naissance_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    naissance_date = models.DateField(null=True)
    naissance_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    deces_annee = models.SmallIntegerField(null=True, blank=True, default='')
    deces_mois = models.SmallIntegerField(null=True, blank=True, default='')
    deces_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    deces_date = models.DateField(null=True)
    deces_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    note_biographique = models.CharField(max_length=2048, null=True, blank=True, default='')
    liste = models.SmallIntegerField(null=False, default=0, choices=CHOIX_LISTE)
    origine_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='personne_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='personne_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom + ', ' + self.prenom


class Traversee(models.Model):
    navire = models.ForeignKey(Navire, on_delete=models.RESTRICT, related_name='a_fait', null=False)
    objectif = models.CharField(max_length=50, null=True, blank=True, default='')
    depart_annee = models.SmallIntegerField(null=True, blank=True, default='')
    depart_mois = models.SmallIntegerField(null=True, blank=True, default='')
    depart_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    depart_date = models.DateField(null=True)
    depart_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    arrivee_annee = models.SmallIntegerField(null=True, blank=True, default='')
    arrivee_mois = models.SmallIntegerField(null=True, blank=True, default='')
    arrivee_jour  = models.SmallIntegerField(null=True, blank=True, default='')
    arrivee_date = models.DateField(null=True)
    arrivee_lieu = models.CharField(max_length=100, null=True, blank=True, default='')
    destination = models.CharField(max_length=100, null=True, blank=True, default='')
    retour = models.CharField(max_length=100, null=True, blank=True, default='')
    notes_equipage_passagers = models.CharField(max_length=2048, null=True, blank=True, default='')
    observations = models.CharField(max_length=4096, null=True, blank=True, default='')
    nb_autres_navires = models.SmallIntegerField(null=False, default=0)
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='traversee_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='traversee_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.navire.nom + '-' + str(self.depart_annee) + '-' + self.depart_lieu


class Autre_Navire_Traversee(models.Model):
    navire = models.ForeignKey(Navire, on_delete=models.RESTRICT, related_name='etait_dans', null=False)
    traversee = models.ForeignKey(Traversee, on_delete=models.CASCADE, related_name='comportait_aussi', null=False)
    observations = models.CharField(max_length=2048, null=True, blank=True, default='')
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='autre_navire_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='autre_navire_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)


class Voyage(models.Model):
    CHOIX_ROLE = [
        (0, "Indéfini"),
        (2, "Capitaine"),
        (6, "Contrôleur"),
        (1, "Maître"),
        (4, "Membre d'équipage"),
        (5, "Passager"),
        (3, "Pilote"),
    ]
    personne = models.ForeignKey(Personne, on_delete=models.RESTRICT, related_name='voyage_effectue', null=False)
    annee = models.SmallIntegerField(null=True, blank=True, default='')
    sequence = models.SmallIntegerField(null=False, default=1)
    destination = models.CharField(max_length=100, null=True, blank=True, default='')
    navire_nom = models.CharField(max_length=100, null=True, blank=True, default='')
    traversee = models.ForeignKey(Traversee, on_delete=models.RESTRICT, related_name='liste_passagers', null=True, default=None)
    role = models.SmallIntegerField(null=False, default=0, choices=CHOIX_ROLE)
    uk = models.UniqueConstraint(name='voyage_uk', fields=["personne_id", "annee", "sequence"])
    aud_crt_user = models.ForeignKey(User,on_delete=models.RESTRICT, related_name='voyage_creee_par', default=1)
    aud_crt_ts = models.DateTimeField(auto_now_add=True, null=True)
    aud_upd_user = models.ForeignKey(User,on_delete=models.RESTRICT, null=True, related_name='voyage_maj_par')
    aud_upd_ts = models.DateTimeField(auto_now=True)

navires/nnf/templates/traversees/ajout.html
{% extends 'base.html' %}

{% block title %}Ajouter une traversée de navire{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Ajouter une traversée pour le {{ navire.nom }}</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                            <a href="{% url 'nnf:modifier_navire' navire.id %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/traversees/detail.html
{% extends "base.html" %}

{% block title %}Traversée - Vue détaillée{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Vue détaillée: {{ traversee.depart_annee }}</h1>
        </div>
        <p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Attribut</th>
                        <th scope="col">Valeur</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Navire</td>
                        {% if traversee.navire %}
                            <td>{{ traversee.navire.nom }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Objectif</td>
                        {% if traversee.objectif %}
                            <td>{{ traversee.objectif }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Départ</td>
                        {% if traversee.depart_lieu %}
                            <td>{{ traversee.depart_lieu }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Date de départ</td>
                        <td>
                            {% if traversee.depart_date %}
                                {{ traversee.depart_date }}
                            {% elif traversee.depart_annee %}
                                {{ traversee.depart_annee }}
                            {% else %}
                                Inconnue
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Arrivée</td>
                        {% if traversee.arrivee_lieu %}
                            <td>{{ traversee.arrivee_lieu }}</td>
                        {% else %}
                            <td>Inconnue</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Date d'arrivée</td>
                        <td>
                            {% if traversee.arrivee_date %}
                                {{ traversee.arrivee_date }}
                            {% elif traversee.arrivee_annee %}
                                {{ traversee.arrivee_annee }}
                            {% else %}
                                Inconnue
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Destination</td>
                        {% if traversee.destination %}
                            <td>{{ traversee.destination }}</td>
                        {% else %}
                            <td>Inconnue</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Retour</td>
                        {% if traversee.retour %}
                            <td>{{ traversee.retour }}</td>
                        {% else %}
                            <td>Inconnu</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Autres navires</td>
                        <td>{{ traversee.nb_autres_navires }}</td>
                    </tr>
                    <tr>
                        <td>Ajouté par</td>
                        <td>{{ traversee.aud_crt_user.username }}</td>
                    </tr>
                    <tr>
                        <td>Ajouté le</td>
                        <td>{{ traversee.aud_crt_ts }}</td>
                    </tr>
                    {% if traversee.aud_upd_user %}
                        <tr>
                            <td>Mis à jour par</td>
                            <td>{{ traversee.aud_upd_user.username }}</td>
                        </tr>
                        <tr>
                            <td>Mis à jour le</td>
                            <td>{{ traversee.aud_upd_ts }}</td>
                        </tr>
                    {% endif %}
                    </tbody>
            </table>
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Note équipage/passagers</h3>
                    <p class="card-text">{{ traversee.notes_equipage_passagers }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Observations</h3>
                    <p class="card-text">{{ traversee.observations}}</p>
                </div>
            </div>
        <hr />
        <h3>Passagers</h3>
        <ul class="list-group">
            {% if passagers %}
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Rôle</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in passagers %}
                            <tr>
                                <td>
                                    <a href="#">{{ p.personne.nom }}, {{ p.personne.prenom }}</a>
                                </td>
                                <td>{{ p.get_role_display }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Pas de passagers.
            {% endif %}
        </ul>
        </p>
        <p>
            <a href="{% url 'nnf:liste_traversees' %}" class="btn btn-primary">Retour à la liste</a>
        </p>
    </div>
{% endblock %}

navires/nnf/templates/traversees/liste.html
{% extends "base.html" %}

{% block title %}Liste des traversées{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Liste des Traversées</h1>
    </div>
    <p>
        <table id="table"
               data-toggle="table"
               data-search="true"
               data-show-columns="true"
               data-pagination="true"
               data-page-size="25"
               data-page-list="[25, 50, 100, 250, 500, all]"
               data-response-handler="responseHandler">
            <thead>
                <tr>
                    <th data-field="annee" data-sortable="true">Année</th>
                    <th data-field="navire" data-sortable="true">Navire</th>
                    <th data-field="origine" data-sortable="true">Origine</th>
                    <th data-field="destination" data-sortable="true">Destination</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for t in traversees %}
                    <tr>
                        <td>
                            {{ t.depart_annee }}
                        </td>
                        <td>{% if t.navire %}
                                {{ t.navire.nom }}
                            {% else %}
                                Inconnu
                            {% endif %}
                        </td>
                        <td>{% if t.depart_lieu %}
                                {{ t.depart_lieu }}
                            {% else %}
                                Inconnu
                            {% endif %}
                        </td>
                        <td>{% if t.arrivee_lieu %}
                                {{ t.arrivee_lieu }}
                            {% else %}
                                Inconnue
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'nnf:detail_traversee' t.id %}"
                               class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Détail">
                                <span class="bi-eye"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

navires/nnf/templates/traversees/modif.html
{% extends 'base.html' %}

{% block title %}Modifier une traversée de navire{% endblock %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Modifier une traversée pour le {{ traversee.navire.nom }}</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Modifier</button>
                            <a href="{% url 'nnf:modifier_navire' traversee.navire.id %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <h4>Autres navires dans la traversée</h4>
        {% if traversee.comportait_aussi.all %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for n in traversee.comportait_aussi.all %}
                        <tr>
                            <td>{{ n.navire.nom }}</td>
                            <td>
                                <a href="{% url 'nnf:detail_autre_navire_traversee' n.id  %}"
                                    class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Détail">
                                    <span class="bi-eye"></span>
                                </a>
                                <a href="{% url 'nnf:modifier_autre_navire_traversee' n.id %}"
                                    class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier">
                                    <span class="bi-pencil"></span>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Pas d'autre navire.</p>
        {% endif %}
        <a href="{% url 'nnf:ajout_autre_navire_traversee' traversee.id %}" class="btn btn-primary">Ajouter un navire</a>
    </div>
</div>
{% endblock content %}

navires/nnf/templates/traversees/supp.html
{% extends "base.html" %}

{% block title %}Supprimer une traversée{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Supprimer cette traversée du navire {{ traversee.navire.nom }}</h1>
        </div>
        <div class="module">
            <form action="" method="post">
                {% csrf_token %}
                <p>Es-tu sûr de vouloir supprimer cette traversée?</p>
                <p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Attribut</th>
                                <th scope="col">Valeur</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Année</td>
                                <td>{{ traversee.depart_annee }}</td>
                            </tr>
                            <tr>
                                <td>Départ de</td>
                                {% if traversee.depart_lieu %}
                                    <td>{{ traversee.depart_lieu }}</td>
                                {% else %}
                                    <td>Inconnu</td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>
                </p>
                <p>
                    <button type="submit" class="btn btn-primary">Oui</button>
                    <a href="{% url 'nnf:modifier_navire' traversee.navire.id %}" class="btn btn-primary">Non</a>
                </p>
            </form>
        </div>
    </div>
{% endblock %}